"""
Fast inference-only evaluation of the open-box shortwave radiative
transfer network on NVIDIA GPUs.

15X faster than the original version (evaluate_network.py) 
on an NVDIA T4 GPU

Key changes:

  * The Scattering module was and still is the largest computational bottleneck. To greatly reduce its cost, we wrote custom Triton kernels. There are several alternative computational pathways.
  By default, the current pathway is the most efficient one for the T4 GPU. However, the other pathways may be more efficient for other architectures and have not been removed from the code. See below and `fused_scattering_T4.py`.

  * Multireflection and Propagationis are replaced by a single fused Triton kernel.  See below and `fused_multireflection_propagation.py`.

  * The test loop accumulates loss values into a GPU-resident tensor
    rather than calling `.item()` on every loss for every batch
    (`.item()` forces a host/device sync).  Loss values are copied
    back to the host once at the end of the year.

  * The default batch size is increased to 8192 columns to amortize
    kernel launch and Python overhead across many more samples per
    iteration.  Larger DataLoader prefetching is also enabled.

Author: Henry Schneiderman, henry@pittdata.com
Code generated by Anthropic's Claude Code
"""

import os
import sys
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F
import time

import xarray as xr

import multireflection_timing
import multiple_mlps
import train_network as tn
import data_generation
import network_losses as nl

import fused_scattering_T4 as fused_scattering
import fused_propagation
import fused_multireflection_propagation

torch.set_float32_matmul_precision('high')
default_float_type = torch.float32

# Cumulative wall-clock time across years (only used for human-readable
# reporting; not on the critical path).
t_total = 0.0

# ---------------------------------------------------------------------------
# Per-stage timers (diagnostic).   TIMING_ENABLED is True will
# insert torch.cuda.synchronize() between stages so that wall time
# can be attributed to each.  This adds host/device sync overhead and is
# off the critical path of the optimized run — flip TIMING_ENABLED back
# to False for operational use.
# ---------------------------------------------------------------------------
TIMING_ENABLED = os.environ.get("TIMING_ENABLED", "1") == "1"

# Various measures of accuracy
METRICS_ENABLED = os.environ.get("METRICS_ENABLED", "1") == "1"

# Environmental variables below select the computational pathway.

# Default settings of these variables are optimized for the T4 GPU

# Split into separate kernels for direct and diffuse radiation
# Will make unnecessary split, transpose, and join operations in handling
# block diagonal matrix 
# Initially, generated by Claude Code
# DO NOT USE
USE_BD_SCATTERING = os.environ.get("SCATTERING_BD", "0") == "1"
# Split into separate kernels for direct and diffuse radiation
# Removes unnecessary split, transpose, and join operations in handling
# block diagonal matrix in USE_BD_SCATTERING
# Leads to better performance on T4 GPU
# CURRENT DEFAULT
USE_BD_V2_SCATTERING = os.environ.get("SCATTERING_BD_V2", "1") == "1"
# Split into separate kernels for "left" and "right"
# matrix blocks for both direct and diffuse radiation,
# giving 4 total kernels
# Goal was to reduce pressure on registers but incurs additional I/O
# to global memory that is very costly
USE_BD_V2_SPLIT_SCATTERING = os.environ.get("SCATTERING_BD_V2_SPLIT", "0") == "1"
# Puts all computation (direct and diffuse, left and right blocks)
# together in a single kernel. Avoids some duplicated computation.
# However, isn't faster for T4 GPU probably because of register
# spilling and oversubscribed L1 Cache. 
# Somewhat slower on L4 
USE_BD_V2_COMBINED_SCATTERING = os.environ.get("SCATTERING_BD_V2_COMBINED", "0") == "1"

# Fuses multireflection kernel with propagation kernel
# Leads to better performance on T4 GPU. 
# Should see the same with more powerful GPUs
# CURRENT DEFAULT
USE_FUSED_MULTIREF_PROP = os.environ.get("FUSED_MULTIREF_PROP", "1") == "1"
# Fused optical depth and scattering in single kernel
# Does not take advantage of block diagonal structure
# Does not lead to better performance on T4
# if USE_BD_V2_COMBINED_SCATTERING shows improvement on faster
# GPUs (e.g., L4 and better), this is worth testing
# However, if that's the case, this should be re-writen to take
# advantage of block diagonal structure
USE_FKE_SCATTERING = os.environ.get("SCATTERING_FKE", "0") == "1"

# Variables used to time code execution
t_optical_depth = 0.0
t_scattering    = 0.0
t_multireflection = 0.0
t_propagation   = 0.0
t_input_flux    = 0.0
t_loss          = 0.0
t_data_to_gpu   = 0.0

def _reset_stage_timers():
    global t_optical_depth, t_scattering, t_multireflection, t_propagation
    global t_input_flux, t_loss, t_data_to_gpu
    t_optical_depth = 0.0
    t_scattering    = 0.0
    t_multireflection = 0.0
    t_propagation   = 0.0
    t_input_flux    = 0.0
    t_loss          = 0.0
    t_data_to_gpu   = 0.0


def _print_stage_timers():
    print(f"  t_data_to_gpu     = {t_data_to_gpu:.4f} s")
    print(f"  t_optical_depth   = {t_optical_depth:.4f} s")
    print(f"  t_scattering      = {t_scattering:.4f} s")
    print(f"  t_multireflection = {t_multireflection:.4f} s")
    print(f"  t_input_flux      = {t_input_flux:.4f} s")
    print(f"  t_propagation     = {t_propagation:.4f} s")
    print(f"  t_loss            = {t_loss:.4f} s")


# ---------------------------------------------------------------------------
# ScatteringFused module
# ---------------------------------------------------------------------------
class ScatteringFused(nn.Module):
    """
    Replacement for Scattering that does the entire scattering
    pipeline using Triton kernel launches.

    Holds parameters with names compatible with the original Scattering
    class so that an existing checkpoint can be loaded directly via
    `load_state_dict`.  After loading, `reconfigure(device)` must be
    called to copy the network's weights into the
    kernels.
    """

    def __init__(self, n_channel, n_constituent, dropout_p, device):
        super().__init__()
        self.n_channel = n_channel
        self.device = device

        # Same names as in the original Scattering so that
        # the parameter keys in the state_dict line up.
        # These routines are not called in the computation
        self.direct_scattering = multiple_mlps.MultipleMLPs_I9_Triton(
            n_inputs=n_constituent + 1, n_hidden_layers=3,
            n_channels=n_channel, dropout_p=dropout_p, device=device,
            bias=True, requires_grad=False)

        self.diffuse_scattering = multiple_mlps.MultipleMLPs_I8_Triton(
            n_inputs=n_constituent, n_hidden_layers=3,
            n_channels=n_channel, dropout_p=dropout_p, device=device,
            bias=True, requires_grad=False)

        # Per-channel selection weights, kept as Conv2d so that the
        # checkpoint key `direct_selection.weight` /
        # `diffuse_selection.weight` matches.  The Conv2d is never
        # actually called in the computation.
        self.direct_selection = nn.Conv2d(
            in_channels=n_channel, out_channels=n_channel,
            kernel_size=(8, 1), stride=(1, 1), padding=0, dilation=1,
            groups=n_channel, bias=False, device=device)

        self.diffuse_selection = nn.Conv2d(
            in_channels=n_channel, out_channels=n_channel,
            kernel_size=(8, 1), stride=(1, 1), padding=0, dilation=1,
            groups=n_channel, bias=False, device=device)

    def reset_dropout(self, dropout_p):
        self.direct_scattering.reset_dropout(dropout_p)
        self.diffuse_scattering.reset_dropout(dropout_p)

    def reconfigure(self, device):
        # Copy weights from original model to optimized model
        
        # Materialize "Multiple MLP" weight buffers (W0/B0/Wh0/Bh0/Wh1/Bh1/Wo/Bo)
        self.direct_scattering.reconfigure(device=device)
        self.diffuse_scattering.reconfigure(device=device)

        # Cache contiguous flat selection weight tensors of shape
        # [n_channel, 8].  The Conv2d weight has shape
        # [n_channel, 1, 8, 1] which is already contiguous, so the
        # reshape is a free view.
        with torch.no_grad():
            self.register_buffer(
                'wsel_direct',
                self.direct_selection.weight.detach()
                    .reshape(self.n_channel, 8).contiguous())
            self.register_buffer(
                'wsel_diffuse',
                self.diffuse_selection.weight.detach()
                    .reshape(self.n_channel, 8).contiguous())

            # Pre-store hidden/output weights as FP16 for T4 tensor cores.
            # Avoids in-kernel FP32->FP16 conversion, reducing shared memory
            # footprint and register pressure.
            for mlp in (self.direct_scattering, self.diffuse_scattering):
                mlp.register_buffer('wh0_f16', mlp.wh0.to(torch.float16).contiguous())
                mlp.register_buffer('wh1_f16', mlp.wh1.to(torch.float16).contiguous())
                mlp.register_buffer('wo_f16',  mlp.wo.to(torch.float16).contiguous())

                # Block-diagonal FP16 storage for the "_bd" kernel variant.
                # Hidden layers are [32,32] block-diagonal with 4 blocks of 8x8.
                # Triton on SM75 requires K>=16 for tl.dot, so we PAIR two
                # 8x8 blocks into a single [16,16] block-diagonal matrix and
                # process two [BLOCK_B,16] x [16,16] matmuls per layer (50%
                # sparse per matmul, but that's still 2x fewer FMAs than one
                # dense [BLOCK_B,32] x [32,32] — which is 75% sparse).
                # Storage: [2, 16, 16] FP16 = two paired slices of the dense
                # [32,32] matrix: [:16,:16] (blocks 0&1) and [16:,16:] (blocks 2&3).
                wh0_pair = torch.stack([
                    mlp.wh0[:16, :16].to(torch.float16),
                    mlp.wh0[16:, 16:].to(torch.float16),
                ], dim=0)
                wh1_pair = torch.stack([
                    mlp.wh1[:16, :16].to(torch.float16),
                    mlp.wh1[16:, 16:].to(torch.float16),
                ], dim=0)
                mlp.register_buffer('wh0_f16_bd', wh0_pair.contiguous())
                mlp.register_buffer('wh1_f16_bd', wh1_pair.contiguous())

                # Split-path (v2) buffers: input and output layers also
                # pre-packed as [2, 16, 16] for the reshape-free BD kernel.
                # Input w0 [16, 32] FP32 → two [16, 16] halves (left/right cols)
                w0_pair = torch.stack([
                    mlp.w0[:, :16],
                    mlp.w0[:, 16:],
                ], dim=0)
                mlp.register_buffer('w0_bd', w0_pair.contiguous())
                # Output wo [32, 32] FP16 → two [16, 16] diagonal blocks
                wo_pair = torch.stack([
                    mlp.wo[:16, :16].to(torch.float16),
                    mlp.wo[16:, 16:].to(torch.float16),
                ], dim=0)
                mlp.register_buffer('wo_f16_bd', wo_pair.contiguous())

    def forward(self, mass_flat, ke_flat, w_eff_filter, mu_dir_flat,
                inv_mu_diffuse_scalar, n_examples, n_layers):
        """Scattering computation

        Inputs (all already on device, all already flattened over the
        sample-layer axis where applicable):
            mass_flat            : [B, 8]              (B = n_examples*n_layers)
            ke_flat              : [B, 6]
            w_eff_filter         : [n_channels, 8]
            mu_dir_flat          : [B]
            inv_mu_diffuse_scalar: Python float
            n_examples, n_layers : ints, used only to view outputs

        Returns the 8 per-layer radiative quantities expected by
        MultiReflectionFast, each shaped [n_examples, n_layers, n_channels].
        """
        n_channels = self.n_channel
        B = mass_flat.shape[0]

        # Output buffers — flat 2D, viewed as 3D for downstream consumers.
        t_full_direct  = torch.empty((B, n_channels), device=self.device, dtype=torch.float32)
        e_t_direct     = torch.empty_like(t_full_direct)
        e_r_direct     = torch.empty_like(t_full_direct)
        e_a_direct     = torch.empty_like(t_full_direct)

        t_full_diffuse = torch.empty_like(t_full_direct)
        e_t_diffuse    = torch.empty_like(t_full_direct)
        e_r_diffuse    = torch.empty_like(t_full_direct)
        e_a_diffuse    = torch.empty_like(t_full_direct)

        # Methods that use block diagonal structure (BD) of scattering
        # algorithm
        if USE_BD_V2_COMBINED_SCATTERING:
            # Puts all computation (direct and diffuse, left and right blocks)
            # together in a single kernels. Avoids some duplicated computation.
            # However, isn't faster for T4 GPU probably because of register
            # spilling and oversubscribed L1 Cache. Needs testing on other
            # GPUs
            _launch = fused_scattering.launch_optical_scattering_combined_bd_v2
        elif USE_BD_V2_SPLIT_SCATTERING:
            # Split into separate kernels for "left" and "right"
            # matric blocks for both direct and diffuse radiation.
            # Total of 4 kernels
            # Goal was to reduce pressure on registers but incurs additional I/O
            # to global memory that is very costly
            _launch = fused_scattering.launch_optical_scattering_bd_v2_split
        elif USE_BD_V2_SCATTERING:
            # Split into separate kernels for direct and diffuse radiation
            # Same as fused_scattering.launch_optical_scattering_bd,
            # except removes unneccessary split, transpose, join operations
            # So far this gives the best performance
            _launch = fused_scattering.launch_optical_scattering_bd_v2
        elif USE_BD_SCATTERING:
            # Split into separate kernels for direct and diffuse radiation
            # Does unnecessary split, transpose, and join operations in handling
            # block diagonal matrix 
            # Initially generated by Claude Code
            _launch = fused_scattering.launch_optical_scattering_bd
        else:
            # Does not take advantage of block diagonal matrix multiply
            _launch = fused_scattering.launch_optical_scattering
        _launch(
            mass_flat, ke_flat, w_eff_filter, mu_dir_flat,
            inv_mu_diffuse_scalar,
            self.direct_scattering, self.diffuse_scattering,
            self.wsel_direct, self.wsel_diffuse,
            t_full_direct,  e_t_direct,  e_r_direct,  e_a_direct,
            t_full_diffuse, e_t_diffuse, e_r_diffuse, e_a_diffuse,
            n_channels)

        return [
            t_full_direct .view(n_examples, n_layers, n_channels),
            t_full_diffuse.view(n_examples, n_layers, n_channels),
            e_t_direct    .view(n_examples, n_layers, n_channels),
            e_r_direct    .view(n_examples, n_layers, n_channels),
            e_a_direct    .view(n_examples, n_layers, n_channels),
            e_t_diffuse   .view(n_examples, n_layers, n_channels),
            e_r_diffuse   .view(n_examples, n_layers, n_channels),
            e_a_diffuse   .view(n_examples, n_layers, n_channels),
        ]

    # Fused optical depth with scattering into single kernel
    # Slower on T4 than separate kernels for optical depth and scattering
    def forward_fke(self, mass_flat, tp_flat, w_eff_filter, mu_dir_flat,
                    inv_mu_diffuse_scalar, ke_weights, n_examples, n_layers):
        """Fused ke+scattering: computes ke inline from temperature/pressure."""
        n_channels = self.n_channel
        B = mass_flat.shape[0]

        t_full_direct  = torch.empty((B, n_channels), device=self.device, dtype=torch.float32)
        e_t_direct     = torch.empty_like(t_full_direct)
        e_r_direct     = torch.empty_like(t_full_direct)
        e_a_direct     = torch.empty_like(t_full_direct)

        t_full_diffuse = torch.empty_like(t_full_direct)
        e_t_diffuse    = torch.empty_like(t_full_direct)
        e_r_diffuse    = torch.empty_like(t_full_direct)
        e_a_diffuse    = torch.empty_like(t_full_direct)

        fused_scattering.launch_optical_scattering_fke(
            mass_flat, tp_flat, w_eff_filter, mu_dir_flat,
            inv_mu_diffuse_scalar,
            ke_weights,
            self.direct_scattering, self.diffuse_scattering,
            self.wsel_direct, self.wsel_diffuse,
            t_full_direct,  e_t_direct,  e_r_direct,  e_a_direct,
            t_full_diffuse, e_t_diffuse, e_r_diffuse, e_a_diffuse,
            n_channels)

        return [
            t_full_direct .view(n_examples, n_layers, n_channels),
            t_full_diffuse.view(n_examples, n_layers, n_channels),
            e_t_direct    .view(n_examples, n_layers, n_channels),
            e_r_direct    .view(n_examples, n_layers, n_channels),
            e_a_direct    .view(n_examples, n_layers, n_channels),
            e_t_diffuse   .view(n_examples, n_layers, n_channels),
            e_r_diffuse   .view(n_examples, n_layers, n_channels),
            e_a_diffuse   .view(n_examples, n_layers, n_channels),
        ]


# ---------------------------------------------------------------------------
# FullNetV3 — orchestrates optical depth, scattering, multireflection, propagation.
# ---------------------------------------------------------------------------
class FullNetV3(nn.Module):
    """Inference-only top-level network.

    State-dict compatible with the original version.  Names
    must therefore line up exactly:

        mu_diffuse_net, spectral_net,
        optical_depth_net.module.<...>,
        scattering_net.<direct|diffuse>_scattering.<...>,
        scattering_net.<direct|diffuse>_selection.weight

    Notably, the original version wraps the scattering module inside a
    `LayerDistributed`, so its state_dict keys begin with
    `scattering_net.module.`.  We therefore wrap our ScatteringFused
    in a thin pass-through `_ScatteringHolder` whose attribute name is
    `module`, in order to keep the keys identical.
    """

    class _ScatteringHolder(nn.Module):
        def __init__(self, inner):
            super().__init__()
            self.module = inner

    def __init__(self, n_channel, n_constituent, dropout_p, device):
        super().__init__()
        with torch.no_grad():
            self.device = device
            self.n_channel = n_channel
            self.solar_constant = 1361.0

            self.mu_diffuse_net = nn.Linear(1, 1, bias=False, device=device)
            torch.nn.init.uniform_(self.mu_diffuse_net.weight, a=0.4, b=0.6)

            self.spectral_net = nn.Linear(1, n_channel, bias=False, device=device)
            torch.nn.init.uniform_(self.spectral_net.weight, a=0.4, b=0.6)

            # OpticalDepth: keep the original PyTorch module 
            # (it is `torch.compile`-decorated
            self.optical_depth_net = tn.LayerDistributed(
                tn.OpticalDepth(n_channel, dropout_p, device))

            # Scattering: fused replacement.  Wrap in a holder so that
            # the state_dict keys read `scattering_net.module.<...>`.
            self.scattering_net = FullNetV3._ScatteringHolder(
                ScatteringFused(n_channel, n_constituent, dropout_p, device))

            # Multireflection: fused Triton kernel.
            self.multireflection_net = multireflection_timing.MultiReflectionFast(device)

            # Propagation: fused Triton kernel.
            self.propagation_net = fused_propagation.PropagationFused(n_channel)

            # Fused multireflection + propagation (optional, behind env var)
            if USE_FUSED_MULTIREF_PROP:
                self.fused_multiref_prop = (
                    fused_multireflection_propagation
                    .MultiReflectionPropagationFused(n_channel, device))

    def reset_dropout(self, dropout_p):
        self.optical_depth_net.reset_dropout(dropout_p)
        self.scattering_net.module.reset_dropout(dropout_p)

    def reconfigure(self, device):
        """
        Copies weights from original model to optimized model.

        Must be called once after `load_state_dict`.
        """
        self.scattering_net.module.reconfigure(device=device)

        # Pre-compute scalars / per-channel constants that depend only
        # on parameters, not on inputs, so that the forward pass does
        # not have to recompute them per batch.
        with torch.no_grad():
            one = torch.ones((1,), dtype=torch.float32, device=self.device)
            spectral = F.softmax(self.spectral_net(one), dim=-1) * self.solar_constant  # [n_ch]
            self.register_buffer('spectral_per_channel', spectral.detach().contiguous())

            mu_diffuse = torch.sigmoid(self.mu_diffuse_net(one)).reshape(())
            # Sync once here (one-time cost) so that the per-batch
            # forward pass can pass a Python float (no tensor read).
            self._inv_mu_diffuse_scalar = float(1.0 / (mu_diffuse.item() + 1.0e-7))

            # Pre-compute W_eff_filter[n_channels, 8] from the loaded
            # OpticalDepth weights.  This is the only piece of optical
            # depth that depends solely on parameters and not on per-row
            # inputs; the per-row tau is computed inside the fused
            # optical+scattering Triton kernel from
            #     mass[b, k] * ke[b, k] * W_eff_filter[c, k].
            od = self.optical_depth_net.module
            n_ch = self.n_channel

            # exp(W) for each gas, shape [n_ch]
            exp_w = torch.zeros(n_ch, 8, dtype=torch.float32, device=self.device)
            exp_w[:, 0] = torch.exp(od.net_lw .weight.reshape(-1))
            exp_w[:, 1] = torch.exp(od.net_iw .weight.reshape(-1))
            exp_w[:, 2] = torch.exp(od.net_h2o.weight.reshape(-1))
            exp_w[:, 3] = torch.exp(od.net_o3 .weight.reshape(-1))
            exp_w[:, 4] = torch.exp(od.net_co2.weight.reshape(-1))
            exp_w[:, 5] = torch.exp(od.net_o2 .weight.reshape(-1))
            exp_w[:, 6] = torch.exp(od.net_n2o.weight.reshape(-1))
            exp_w[:, 7] = torch.exp(od.net_ch4.weight.reshape(-1))

            # Apply the per-gas channel filter (clouds have no filter).
            # exp_w * filter is the only thing the Triton kernel needs.
            w_eff_filter = exp_w.clone()
            w_eff_filter[:, 2] *= od.filter_h2o
            w_eff_filter[:, 3] *= od.filter_o3
            w_eff_filter[:, 4] *= od.filter_co2
            w_eff_filter[:, 5] *= od.filter_o2
            w_eff_filter[:, 6] *= od.filter_n2o
            w_eff_filter[:, 7] *= od.filter_ch4
            self.register_buffer('w_eff_filter', w_eff_filter.contiguous())

            # Pre-pack ke MLP weights for fused ke+scattering kernel.
            # Layout per MLP (71 FP32 scalars):
            #   W0.T [2,6] + b0 [6] + W1.T [6,4] + b1 [4] +
            #   W2.T [4,4] + b2 [4] + W3.T [4,1] + b3 [1]
            # Six MLPs packed sequentially: total 426 scalars.
            if USE_FKE_SCATTERING:
                ke_mlps = [od.net_ke_h2o, od.net_ke_o3, od.net_ke_co2,
                           od.net_ke_o2, od.net_ke_n2o, od.net_ke_ch4]
                parts = []
                for mlp in ke_mlps:
                    parts.append(mlp.hidden[0].weight.T.contiguous().flatten())
                    parts.append(mlp.hidden[0].bias.detach())
                    parts.append(mlp.hidden[1].weight.T.contiguous().flatten())
                    parts.append(mlp.hidden[1].bias.detach())
                    parts.append(mlp.hidden[2].weight.T.contiguous().flatten())
                    parts.append(mlp.hidden[2].bias.detach())
                    parts.append(mlp.output.weight.T.contiguous().flatten())
                    parts.append(mlp.output.bias.detach())
                self.register_buffer('ke_weights_packed',
                                     torch.cat(parts).contiguous())

    @torch.compile(options={"triton.persistent_reductions": True})
    def _compute_ke(self, t_p_flat):
        """Run the six small ke MLPs (h2o, o3, co2, o2, n2o, ch4) with
        torch.compile for fusion, and return their per-row sigmoids
        stacked along the constituent axis.

        t_p_flat: [B, 2]   (temperature, pressure per sample-layer)
        returns:  [B, 6]
        """
        od = self.optical_depth_net.module
        ke_h2o = torch.sigmoid(od.net_ke_h2o(t_p_flat))
        ke_o3  = torch.sigmoid(od.net_ke_o3 (t_p_flat))
        ke_co2 = torch.sigmoid(od.net_ke_co2(t_p_flat))
        ke_o2  = torch.sigmoid(od.net_ke_o2 (t_p_flat))
        ke_n2o = torch.sigmoid(od.net_ke_n2o(t_p_flat))
        ke_ch4 = torch.sigmoid(od.net_ke_ch4(t_p_flat))
        return torch.cat([ke_h2o, ke_o3, ke_co2, ke_o2, ke_n2o, ke_ch4], dim=-1)

    def forward(self, x):
        x_layers, x_surface, _, _, _, = x

        n_examples, n_layers, _ = x_layers.shape
        B = n_examples * n_layers

        # Flatten the (sample, layer) axis once.  Both temperature/
        # pressure and constituent mass need this layout for the fused
        # optical+scattering kernel.
        temperature_pressure = x_layers[:, :, 0:2].reshape(B, 2)
        constituent_mass     = x_layers[:, :, 2:10].reshape(B, 8).contiguous()

        mu_direct = x_surface[:, 0]   # [n_examples]

        mu_dir_flat = mu_direct.unsqueeze(1).expand(n_examples, n_layers).reshape(B).contiguous()

        if TIMING_ENABLED:
            global t_optical_depth, t_scattering

        if USE_FKE_SCATTERING:
            # ---- 1+2. Fused ke+scattering (ke computed inline) ----
            if TIMING_ENABLED:
                torch.cuda.synchronize()
                _t0 = time.time()
            tp_flat = temperature_pressure.contiguous()
            layers = self.scattering_net.module.forward_fke(
                constituent_mass, tp_flat, self.w_eff_filter, mu_dir_flat,
                self._inv_mu_diffuse_scalar, self.ke_weights_packed,
                n_examples, n_layers)
            if TIMING_ENABLED:
                torch.cuda.synchronize()
                t_scattering += time.time() - _t0
        else:
            # ---- 1. Optical depth (ke MLPs only) ----
            if TIMING_ENABLED:
                torch.cuda.synchronize()
                _t0 = time.time()
            ke = self._compute_ke(temperature_pressure)   # [B, 6]
            if TIMING_ENABLED:
                torch.cuda.synchronize()
                t_optical_depth += time.time() - _t0

            # ---- 2. Scattering + remaining optical-depth math (fused) ----
            if TIMING_ENABLED:
                _t0 = time.time()
            layers = self.scattering_net.module(
                constituent_mass, ke, self.w_eff_filter, mu_dir_flat,
                self._inv_mu_diffuse_scalar, n_examples, n_layers)
            if TIMING_ENABLED:
                torch.cuda.synchronize()
                t_scattering += time.time() - _t0

        if TIMING_ENABLED:
            global t_multireflection, t_input_flux, t_propagation

        if USE_FUSED_MULTIREF_PROP:
            # ---- 3+4+5. Fused multireflection + propagation ----
            if TIMING_ENABLED:
                _t0 = time.time()
            flux_direct = self.spectral_per_channel.unsqueeze(0) * mu_direct.unsqueeze(1)
            flux_diffuse = torch.zeros_like(flux_direct)
            flux = self.fused_multiref_prop(
                layers, x_surface, [flux_direct, flux_diffuse])
            if TIMING_ENABLED:
                torch.cuda.synchronize()
                t_multireflection += time.time() - _t0

            (flux_down_direct, flux_down_diffuse, flux_up_diffuse,
             flux_absorbed) = flux
        else:
            # ---- 3. Multireflection (fused Triton kernel) ----
            if TIMING_ENABLED:
                _t0 = time.time()
            multireflected_layers, upward_reflection_toa = \
                self.multireflection_net((layers, x_surface,))
            if TIMING_ENABLED:
                torch.cuda.synchronize()
                t_multireflection += time.time() - _t0

            # ---- 4. Build input flux ----
            if TIMING_ENABLED:
                _t0 = time.time()
            # flux_direct[i, c] = spectral_per_channel[c] * mu_direct[i]
            flux_direct = self.spectral_per_channel.unsqueeze(0) * mu_direct.unsqueeze(1)
            flux_diffuse = torch.zeros_like(flux_direct)
            input_flux = [flux_direct, flux_diffuse]
            if TIMING_ENABLED:
                torch.cuda.synchronize()
                t_input_flux += time.time() - _t0

            # ---- 5. Propagation (fused Triton kernel) ----
            if TIMING_ENABLED:
                _t0 = time.time()
            flux = self.propagation_net((multireflected_layers,
                                        upward_reflection_toa,
                                        input_flux))
            if TIMING_ENABLED:
                torch.cuda.synchronize()
                t_propagation += time.time() - _t0

            (flux_down_direct, flux_down_diffuse, flux_up_diffuse,
             flux_absorbed) = flux

        return [flux_down_direct, flux_down_diffuse, flux_up_diffuse, flux_absorbed]


# ---------------------------------------------------------------------------
# GPU-resident dataset and dataloader.
#
# `RTDataSet` lazily reads each month's netCDF the first time the worker
# touches an index in that month, which forces single-worker DataLoader
# usage and stalls the GPU on disk I/O.  For inference the entire year
# fits comfortably in L4 memory (~600 MB), so we read every month-file
# once up-front, concatenate them, and upload the result to the GPU.
# After that, batches are zero-copy slices of the GPU tensors and the
# host loop has no I/O on the critical path.
# ---------------------------------------------------------------------------
class GPUResidentDataset:
    """All-in-memory, GPU-resident replacement for `RTDataSet`.

    Loads each input file via `data_generation.load_data` (so the same
    NaN checks, normalization, daylight selection, and clear-sky logic
    apply), concatenates the per-file tensors along the sample axis,
    and uploads them to the target device once.  After construction the
    object is purely a container of GPU tensors.
    """

    def __init__(self, input_files, is_clear_sky, device,
                 default_float_type=torch.float32):
        x_layers_chunks      = []
        x_surface_chunks     = []
        delta_pressure_chunks = []
        y_chunks             = []
        sites_chunks         = []

        for file_index, path in enumerate(input_files):
            ds = xr.open_dataset(path)
            try:
                x_layers, x_surface, delta_pressure, y, sites = \
                    data_generation.load_data(
                        ds, file_index, is_clear_sky=is_clear_sky,
                        default_float_type=default_float_type)
            finally:
                ds.close()
            x_layers_chunks.append(x_layers)
            x_surface_chunks.append(x_surface)
            delta_pressure_chunks.append(delta_pressure)
            y_chunks.append(y)
            sites_chunks.append(sites)

        # Concatenate on CPU then move to GPU in one shot per tensor —
        # this avoids 12 separate H2D transfers and minimizes the
        # number of `cudaMalloc` calls.
        self.x_layers       = torch.cat(x_layers_chunks,       dim=0).to(device, non_blocking=True)
        self.x_surface      = torch.cat(x_surface_chunks,      dim=0).to(device, non_blocking=True)
        self.delta_pressure = torch.cat(delta_pressure_chunks, dim=0).to(device, non_blocking=True)
        self.y              = torch.cat(y_chunks,              dim=0).to(device, non_blocking=True)
        self.sites          = torch.cat(sites_chunks,          dim=0).to(device, non_blocking=True)

        self.n = self.x_layers.shape[0]
        torch.cuda.synchronize()

    def __len__(self):
        return self.n

    def free(self):
        del self.x_layers, self.x_surface, self.delta_pressure, self.y, self.sites
        torch.cuda.empty_cache()


class GPUDataLoader:
    """Drop-in replacement for `torch.utils.data.DataLoader` over a
    `GPUResidentDataset`.  Each yielded batch is a tuple of GPU tensor
    slices — no host transfer, no copies, no worker processes.

    The trailing partial batch is PADDED to `batch_size` by wrapping
    around to the beginning of the dataset, so every batch has the
    same size and Triton's autotune cache (keyed on B_total) stays
    warm.  Each iteration yields `(data_tuple, n_valid)` where
    `n_valid` is the number of real (non-padded) samples in the batch
    (equal to `batch_size` for full batches).  Consumers should run
    the model on the full padded batch (for a constant shape) and
    then slice outputs to `[:n_valid]` before computing metrics.
    """

    def __init__(self, dataset, batch_size):
        self.dataset = dataset
        self.batch_size = batch_size

    def __len__(self):
        return (self.dataset.n + self.batch_size - 1) // self.batch_size

    def __iter__(self):
        ds = self.dataset
        bs = self.batch_size
        n = ds.n
        for i in range(0, n, bs):
            if i + bs <= n:
                # Full batch — slice directly
                data = (ds.x_layers[i:i+bs],
                        ds.x_surface[i:i+bs],
                        ds.delta_pressure[i:i+bs],
                        ds.y[i:i+bs],
                        ds.sites[i:i+bs])
                yield data, bs
            else:
                # Partial batch — pad by wrapping around to the start
                n_valid = n - i
                n_pad = bs - n_valid
                data = (torch.cat([ds.x_layers[i:n], ds.x_layers[:n_pad]]),
                        torch.cat([ds.x_surface[i:n], ds.x_surface[:n_pad]]),
                        torch.cat([ds.delta_pressure[i:n], ds.delta_pressure[:n_pad]]),
                        torch.cat([ds.y[i:n], ds.y[:n_pad]]),
                        torch.cat([ds.sites[i:n], ds.sites[:n_pad]]))
                yield data, n_valid


# ---------------------------------------------------------------------------
# Fast test loop — no per-iteration syncs, GPU-resident loss accumulation.
# ---------------------------------------------------------------------------
def test_loop_fast(dataloader, model, loss_functions, loss_names,
                   loss_weights, device):
    model.eval()

    n_loss = len(loss_functions)
    num_batches = len(dataloader)
    # Loss accumulator lives on the GPU; copied to host once at the end.
    loss_acc = torch.zeros(n_loss, device=device, dtype=torch.float32)

    _reset_stage_timers()
    global t_data_to_gpu, t_loss

    # `t_compute` is the GPU-only time, matching original's `t_delt`.  It
    # syncs around the model's computation (and loss accumulation) but
    # NOT around the data-loading wait, so it isolates the work that
    # actually runs on the GPU from any host-side I/O stalls.
    t_compute = 0.0

    torch.cuda.synchronize()
    t_start = time.time()
    with torch.inference_mode():
        for data, n_valid in dataloader:
            if TIMING_ENABLED:
                _t0 = time.time()
            data = [x.to(device, non_blocking=True) for x in data]
            if TIMING_ENABLED:
                torch.cuda.synchronize()
                t_data_to_gpu += time.time() - _t0

            torch.cuda.synchronize()
            t_fwd0 = time.time()
            # Run model on full padded batch to keep B_total constant
            # (so Triton's autotune cache hits on every call).
            y_pred = model(data)

            if TIMING_ENABLED:
                _t0 = time.time()
            # Slice to valid rows only before computing loss (ignore
            # padded duplicates).  Full batches have n_valid == batch_size
            # so slicing is a no-op.
            if n_valid < data[0].shape[0]:
                data_v = [x[:n_valid] for x in data]
                y_pred_v = tuple(
                    p[:n_valid] if isinstance(p, torch.Tensor) else p
                    for p in y_pred)
            else:
                data_v = data
                y_pred_v = y_pred
            for i, loss_fn in enumerate(loss_functions):
                loss_acc[i] = loss_acc[i] + loss_fn(data_v, y_pred_v, loss_weights)
            if TIMING_ENABLED:
                torch.cuda.synchronize()
                t_loss += time.time() - _t0

            torch.cuda.synchronize()
            t_compute += time.time() - t_fwd0
    torch.cuda.synchronize()
    t_delta = time.time() - t_start

    loss = (loss_acc / num_batches).cpu().numpy()

    print("Test Error:")
    for i, value in enumerate(loss):
        print(f" {loss_names[i]}: {value:.4f}")
    print(f"Time evaluation (w/o data I/O)         = {t_compute:.4f} s")
    print(f"Time evaluation (incl. data I/O wait)  = {t_delta:.4f} s")
    if TIMING_ENABLED:
        _print_stage_timers()
    print("")

    return loss, t_delta


# ---------------------------------------------------------------------------
# Top-level entry point.
# ---------------------------------------------------------------------------
def evaluate_network_analysis(base_prefix, data_prefix):
    """Fast inference-only evaluation, mirrors v2's `evaluate_network_analysis`."""

    base_dir = base_prefix + "shortwave_radiative_transfer/"
    model_dir = base_dir + "models/"
    model_name_prefix = 'openbox.shortwave.'

    if tn.__name__ == 'train_network':
        model_id = "v2."
        n_epoch = 596
        n_channel = 42
    elif tn.__name__ == 'train_network_5':
        model_id = "v5.1."      # 28 channels instead of 42 
        n_epoch = 669
        n_channel = 28
    else:
        print(f"Not implemented for {tn.__name__}")
        return

    mode = "testing"
    processed_data_dir = data_prefix + "testing/"
    years = ("2009", "2015", "2020")

    print("Pytorch version:", torch.__version__)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using {device} device")
    if device.type == "cuda":
        print('__CUDNN VERSION:', torch.backends.cudnn.version())
        print('__Number CUDA Devices:', torch.cuda.device_count())
        print('__CUDA Device Name:', torch.cuda.get_device_name(0))
        print('__CUDA Device Total Memory [GB]:',
              torch.cuda.get_device_properties(0).total_memory / 1e9)
        print(f'Device capability = {torch.cuda.get_device_capability()}')

    # 8192-column batch comfortably fits L4 memory and amortizes the
    # per-batch Python/launch overhead across ~500K (sample, layer)
    # rows of the scattering kernel.  Larger batches regress because
    # the L1 cache is already saturated at this B_total; more
    # concurrent blocks just evict each other's hot weights.
    batch_size = 8192
    n_constituent = 8

    # Build model and load checkpoint
    model = FullNetV3(n_channel, n_constituent, dropout_p=0, device=device)
    model = model.to(device=device)

    model_filename = model_dir + f"{model_name_prefix}{model_id}"
    loss_weights = tn.get_loss_weights(n_epoch)
    checkpoint = torch.load(model_filename + str(n_epoch).zfill(3),
                            map_location=torch.device(device),
                            weights_only=False)
    print(f"Loaded Model: epoch = {n_epoch}")
    model.load_state_dict(checkpoint['model_state_dict'])

    # Copy weights from original model to optimized model
    model.reconfigure(device=device)

    years = ("2009", "2015", "2020")
    for _ in range(1):
        for year in years:
            test_input_dir = f"{processed_data_dir}{year}/"
            months = [str(m).zfill(2) for m in range(1, 13)]
            test_input_files = [
                f'{test_input_dir}shortwave-{mode}-{year}-{month}.nc'
                for month in months]

            print(f"Loading {mode} dataset for {year}")
            # Read all 12 month-files once and upload to GPU.  After this
            # call there is no disk or host I/O on the per-batch hot path.
            torch.cuda.synchronize()
            _t_load_start = time.time()
            test_dataset = GPUResidentDataset(
                test_input_files, is_clear_sky=False, device=device)
            torch.cuda.synchronize()
            print(f"Year {year}: loaded {len(test_dataset)} samples to GPU "
                f"in {time.time() - _t_load_start:.2f} s")

            test_dataloader = GPUDataLoader(test_dataset, batch_size)

            loss_flux_0_01 = nl.mu_selector_flux_maker(0.01, nl.total_rmse)
            loss_flux_0_05 = nl.mu_selector_flux_maker(0.05, nl.total_rmse)
            loss_flux_0_10 = nl.mu_selector_flux_maker(0.10, nl.total_rmse)

            if METRICS_ENABLED:
                loss_functions = (
                    nl.openbox_rmse,
                    nl.flux_rmse, nl.heating_rate_rmse,
                    nl.direct_flux_rmse, nl.diffuse_flux_rmse,
                    nl.flux_bias, nl.downwelling_flux_rmse, nl.upwelling_flux_rmse,
                    nl.downwelling_flux_bias, nl.upwelling_flux_bias,
                    nl.direct_extinction_rmse,
                    nl.diffuse_heating_rate_rmse,
                    nl.heating_rate_bias,
                    loss_flux_0_01, loss_flux_0_05, loss_flux_0_10)

                loss_names = (
                    "Openbox RMSE",
                    "Flux RMSE", "Heating Rate RMSE",
                    "Direct Flux RMSE", "Diffuse Flux RMSE",
                    "Flux Bias", "Flux Down RMSE", "Flux up RMSE",
                    "Flux Down Bias", "Flux up Bias ",
                    "Direct Extinction RMSE",
                    "Diffuse Heating Rate RMSE",
                    "Heating Rate Bias",
                    "RMSE_flux_0_01", "RMSE_flux_0_05", "RMSE_flux_0_10")
            
            else:
                loss_functions = (
                    nl.flux_rmse, nl.heating_rate_rmse)

                loss_names = (
                    "Flux RMSE", "Heating Rate RMSE")
            
            torch.cuda.synchronize()
            t_0 = time.time()
            _, _ = test_loop_fast(test_dataloader, model,
                                loss_functions, loss_names,
                                loss_weights, device)
            torch.cuda.synchronize()
            t_1 = time.time()
            t_delta = t_1 - t_0
            global t_total
            t_total += t_delta
            print(f"Evaluation time (including data I/O) = {t_delta:.4f} s")
            print(" ")
            print(f"Total evaluation time = {t_total:.4f} s")

            # Report which Triton autotune configs won, per unique B_total.
            # Only the T4 split kernels are used in the production path.
            from fused_scattering_T4 import (
                _optical_split_direct_T4_kernel,
                _optical_split_diffuse_T4_kernel,
            )
            print("=== Triton autotune winners ===")
            for name, k in [("direct",  _optical_split_direct_T4_kernel),
                            ("diffuse", _optical_split_diffuse_T4_kernel)]:
                for key, cfg in k.cache.items():
                    print(f"  {name:8s} key={key}  ->  {cfg}")

            # Release this year's GPU tensors before the next year is loaded.
            test_dataset.free()
            del test_dataloader, test_dataset


if __name__ == "__main__":

    # Command line argument to indicate which platform is
    # being used in order to supply appropriate root directories
    if len(sys.argv) == 2:
        if sys.argv[1] == "azure":
            base_prefix = "/home/hws/src/openbox_neural_networks/"
            data_prefix = "/data-T1/hws/CAMS/processed_data/"
        elif sys.argv[1] == "google":
            base_prefix = "/home/henry/src/openbox_dev/"
            data_prefix = "/mnt/disks/data-t1/atmospheric_data/CAMS/processed_data/"
        elif sys.argv[1] == "local":
            base_prefix = "/home/henry/src/openbox_neural_networks/"
            data_prefix = "/srv/data/CAMS/processed_data/"  
        else:
            print(f"Unknown argument {sys.argv[1]}")
            print(f"Usage: python evaluate_network.py [azure | google | local]")
            quit()
    else:
        print(f"Usage: python evaluate_network.py [azure | google | local]")
        quit()
            
    evaluate_network_analysis(base_prefix=base_prefix,
                                  data_prefix=data_prefix)